# Generated by Django 5.0.6 on 2024-06-25 11:04

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        # validators=[contacts.models.validate_phone_number],
                    ),
                ),
                ("city", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="contacts",
        ),
    ]
