# Generated by Django 5.0.6 on 2024-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0002_contacts_delete_curd"),
    ]

    operations = [
        migrations.CreateModel(
            name="contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
